" Author: James Ni (@Limegrass)
set fileformat=unix
set encoding=utf-8
scriptencoding utf-8

let $HOME = substitute($HOME, '\', '/', 'g')    " normalizes for Windows
let $VIMCONFIG = expand('<sfile>:p:h')
set runtimepath^=$VIMCONFIG,$VIMCONFIG/after

let $VIMLOCAL = $VIMCONFIG.'/local'             " machine-locals that shouldn't be committed
set runtimepath^=$VIMLOCAL,$VIMLOCAL/after      " for vim-plug and maybe anything
let $MYVIMRC = expand('<sfile>:p')              " ensure this file is $MYVIMRC

source $VIMCONFIG/function-definitions.vim      " additional functions
source $VIMCONFIG/vim-settings.vim              " minimal settings
source $VIMCONFIG/keymaps.vim                   " must come after function-definitions
source $VIMCONFIG/plugin-settings.vim           " plugins and plugin settings/mappings
