#! /bin/sh

export XDG_SESSION_TYPE=wayland # at the very least, fixes some items not showing in tray
export WAYLAND_DISPLAY=wayland-1 # at the very least, fixes some items not showing in tray
export XDG_CURRENT_DESKTOP=river

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE
systemctl --user restart xdg-desktop-portal xdg-desktop-portal-wlr

mako &
nm-applet &
fcitx5 &

meguca-wm
